footprint: [[-2.5, -2.5], [-2.5, 2.5], [2.5, 2.5], [2.5, -2.5]]
footprint_padding: 4.0

robot_base_frame: wamv/base_link
update_frequency: 4.0
publish_frequency: 4.0
transform_tolerance: 0.5
always_send_full_costmap: true  # to convert occupancy grid iint opencv image

resolution: 0.30         # 0.20 looked nice

obstacle_range: 50.0
raytrace_range: 50.0

#layer definitions
static:
    map_topic: /odom
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {sensor_frame: wamv/lidar_wamv_link, data_type: LaserScan, clearing: true, marking: true, topic: scan_converter, inf_is_valid: true}

obstacles_pc:
    observation_sources: pointcloud
    #pointcloud: {sensor_frame: wamv/lidar_wamv_link, data_type: PointCloud2, clearing: false, marking: true, topic: /wamv/sensors/lidars/lidar_wamv/points}
    pointcloud: {sensor_frame: wamv/lidar_wamv_link, data_type: PointCloud2, clearing: false, marking: true, topic: /lidar_fenced}

inflation:
    inflation_radius: 3
