global_costmap:
    global_frame: wamv/odom   # (odom)
    robot_base_frame: wamv/base_link
    update_frequency: 2.0
    static_map: false
    rolling_window: false   # false
    track_unknown_space: true

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}


